// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

// Flat config generated by @nuxt/eslint (`nuxt prepare` writes
// .nuxt/eslint.config.mjs). Formatting is Prettier's job, so stylistic rules
// are disabled in nuxt.config.ts.
export default withNuxt(
  {
    ignores: ['wasm/**/pkg*/**', 'wasm/**/target/**', '.output/**', 'dist/**'],
  },
  {
    rules: {
      // Prettier self-closes void elements in SFC templates; don't fight it.
      'vue/html-self-closing': 'off',
      // Typed optional props in <script setup> default to undefined by design.
      'vue/require-default-prop': 'off',
    },
  },
)
