import type { ApngBackend } from '../types'
import type { RenderFrame } from '../../types'

/**
 * Rust→WASM APNG backend (spec §5, decision: build our own). Mirrors the
 * upng-js backend's interface so it can be swapped via setApngBackend().
 *
 * The wasm-pack output lives at wasm/apng-encoder/pkg and is loaded lazily so
 * the app works without it (upng-js remains the default until this is enabled).
 * Enable with `enableWasmApngBackend()` once `npm run wasm:build` has produced
 * the pkg.
 */

interface WasmModule {
  default?: (input?: unknown) => Promise<unknown>
  encode_apng: (
    rgbaAll: Uint8Array,
    width: number,
    height: number,
    count: number,
    delayMs: number,
    loopCount: number,
  ) => Uint8Array
}

let wasm: WasmModule | null = null
let initPromise: Promise<WasmModule> | null = null

async function loadWasm(): Promise<WasmModule> {
  if (wasm) return wasm
  if (initPromise) return initPromise

  initPromise = (async () => {
    // Dynamic import so a missing pkg doesn't break the bundle. The path is
    // resolved at build time once the pkg exists; until then this throws and
    // the caller falls back to upng-js.
    // @ts-expect-error - pkg is generated by wasm-pack and may not exist yet
    const mod = (await import('../../../wasm/apng-encoder/pkg/apng_encoder.js')) as WasmModule
    if (typeof mod.default === 'function') {
      await mod.default()
    }
    wasm = mod
    return mod
  })()

  return initPromise
}

export const wasmApngBackend: ApngBackend = {
  id: 'wasm',
  async encode(frames: RenderFrame[], opts): Promise<Uint8Array> {
    if (frames.length === 0) throw new Error('No frames to encode')
    const mod = await loadWasm()

    const w = opts.width
    const h = opts.height
    const frameLen = w * h * 4
    const all = new Uint8Array(frameLen * frames.length)
    frames.forEach((f, i) => {
      all.set(f.rgba.subarray(0, frameLen), i * frameLen)
    })
    // Uniform delay from the first frame (optimizeFrames already merged dups);
    // for varied delays we'd extend the wasm API — uniform is fine for presets.
    const delay = frames[0]!.delayMs
    const loopCount = opts.loop ? 0 : 1
    return mod.encode_apng(all, w, h, frames.length, delay, loopCount)
  },
}

/** Check whether the wasm pkg can be loaded in this environment. */
export async function isWasmApngAvailable(): Promise<boolean> {
  try {
    await loadWasm()
    return true
  } catch {
    return false
  }
}
